---
title: "mturk_data_processing"
author: "Masoud Jasbi"
date: "3/7/2017"
output: html_document
---

```{r cars}
library(rjson)
library(tidyverse)
```

```{r}
files <- dir("../1_raw_data/", pattern =".json")
adult_data <- data.frame()

for (file in files) {
  jd <- fromJSON(paste(readLines(paste("../1_raw_data/", file, sep="")), collapse=""))
  id <- data_frame(participant = jd$WorkerId,
                  gender = jd$answers$data$gen,
                  age = jd$answers$data$age,
                  Lang = toupper(jd$answers$data$language),
                  logical_training = jd$answers$data$education,
                  trials = jd$answers$data$trial,
                  response = jd$answers$data$response,
                  duration = jd$answers$data$elapsed_ms,
                  AgeGroup = "adult",
                  aim = jd$answers$data$expt_aim,
                  comments = jd$answers$data$expt_gen
                  )
  
  adult_data <- bind_rows(adult_data, id)
}

write.csv(adult_data, "../2_processed_data/adult_data.csv")
```

