---
title: "project_choice"
author: "Masoud Jasbi"
date: "1/22/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Choice

My dissertation is about children's interpretation of conjunction and disjunction words such as *and* and *or*. The paper I chose for this project is a very recent investigation of children's interpretation of disjunction words in French and Japanese. The authors argue that children interpret a disjunction word such as *or* in two ways: inclusive disjunction and conjunction. In other words, some children interpret *or* like *and*. Adults on the other hand interpret *or* as exclsuive disjunction. In a recent study I found evidence for children's inclusive and some adults' exclusive interpretation of *or*, but not children's conjunctive interpretation. In this project I would like to replicate Tieu et al.'s work and investigate the source of conjunctive interpretations.

Tieu et al. (2016) investigated children's interpretation of the french simple and complex disjunction words *ou*/*soit ... soit* as well as the Japanese ones *ka*/*ka...ka*. Their claims hold for disjunction words crosslinguistically so in this project I investgiate English speaking children's interpretation of *or*/*either ... or*. The authors used a Truth Value Judgement Task (Crain and Thornton 1998) in the form of a guessing game. Videos of a puppet giraffe making predictions about a story were recorded. In each trial, participants saw a picture and heard a story. Then the pre-recorded videos were played: the puppet appeared on the laptop screen and made a guess about what happens next in the story. Then participants saw the rest of the story and had to decide wether the puppet's guess was correct or not by stamping under a happy or sad face on a scorecard. 

The original paper recruited 28 French speaking children, 20 French speaking adults, 18 Japanese speaking children and 21 Japanese speaking adults. I plan to have 30 English speaking adults via Mturk and 30 English speaking children from the Bing Nursery School.  The original paper includes all the French and Japanese sentences with their translations. I use the English translations to create my linguistic stimuli. I would like to contact the authors and ask for the original scenarios used and the prerecorded videos. It is important to re-record English videos that resemble the origianl recorded videos in intonation. I would also like to both run the experiment and record the results on a laptop. So far I have not detected major difficulties that I might face in replicating this study.

